### PR TITLE
Use bitvec for free, full

### PR DESCRIPTION
**Pull request by ronreg-ribdev**

### CODE REVIEW

**Comment by ohAitch** [comment]
Oof certainly substantiates "bitvecs are a hassle to deal with bc you can't get pointers to bits", ty for working through this
What was the issue with `return self.gain(Index(...))`, some unique pointer tangle introduced by the bitvecs?

**Comment by ronreg-ribdev** [comment]
> Oof certainly substantiates "bitvecs are a hassle to deal with bc you can't get pointers to bits", ty for working through this What was the issue with `return self.gain(Index(...))`, some unique pointer tangle introduced by the bitvecs?

Trying to call `self.gain` from within that loop is a double-mutable-pointer borrow that the compiler complains about.

**Comment by ohAitch** [comment]
But why was it not _already_ a double mutable borrow P:

**Comment by ronreg-ribdev** [comment]
> But why was it not _already_ a double mutable borrow P:

I am honestly not sure, the exact compiler error with the direct return of `self.gain` within the loop is:

```
error[E0499]: cannot borrow `*self` as mutable more than once at a time
   --> src/lib.rs:262:28
    |
257 |         for (page, mut full) in self.full.iter_mut().enumerate().filter(|(_, full)| !**full) {
    |                                 ------------------------------------------------------------
    |                                 |
    |                                 first mutable borrow occurs here
    |                                 a temporary with access to the first borrow is created here ...
...
262 |                     return self.gain(Index::of(page, 0, 0));
    |                            ^^^^ second mutable borrow occurs here
...
273 |         }
    |         - ... and the first borrow might be used here, when that temporary is dropped and runs the destructor for type `(usize, BitRef<'_, Mut, Lsb0, BitSafeUsize>)`

For more information about this error, try `rustc --explain E0499`.
```

**Comment by ohAitch** [comment]
Hm on reflection I'm going to leave this at "only willing to do the less ergonomic more optimized thing if a benchmark tells me to", perhaps going through "pack both bits as flags in a vector of 'status' bytes" in the middle. Though I probably need softer verbiage than `FIXME` in that case

**Pull request closed without merging**
