### PR TITLE
Simplify grab_page()

### PR DESCRIPTION
**Pull request by ronreg-ribdev**
Create a new Iterator-implementing type to iterate over the contents of a page, and have
grab_page() return *that*, rather than doing a bunch of messy type casts
in grab_page() itself.

### CODE REVIEW

**Comment by ohAitch** [comment]
(Merging on the assumption this didn't change the output of `tests::main`, which I think is the only transitive dependent)

**Comment by ohAitch** [comment]
I guess it would be neater to also define the *type* in `grab_page` itself, the `impl Iterator` return signature is neater, but I assume defining types in methods is not allowed(else surely I'd have done it for the other single-purpose iterators nearby).

**Comment by ronreg-ribdev** [comment]
> (Merging on the assumption this didn't change the output of `tests::main`, which I think is the only transitive dependent)

It doesn't, output is the same.

**Comment by ronreg-ribdev** [comment]
> I guess it would be neater to also define the _type_ in `grab_page` itself, the `impl Iterator` return signature is neater, but I assume defining types in methods is not allowed(else surely I'd have done it for the other single-purpose iterators nearby).

Actually https://github.com/ohAitch/vlist-rs/pull/8 works fine, as long as you don't try to reference the name of the type outside the function.

**Pull request merged**
