### PR TITLE
Some more explicit tests + minor formatting change

### PR DESCRIPTION
**Pull request by ronreg-ribdev**

### CODE REVIEW

**Comment by ohAitch** [comment]
Keeping the whole-function `Some`s sorry

Especially if the alternative makes things complex enough to warrant a variable in the middle of the 
`match thing.type { x => thing.as.x ... }`

**Comment by ronreg-ribdev** [comment]
> Keeping the whole-function `Some`s sorry
> 
> Especially if the alternative makes things complex enough to warrant a variable in the middle of the `match thing.type { x => thing.as.x ... }`

No worries, that's a pretty minor style thing, it evaluates the same either way. I prefer to assign explicit names to intermediate computations more often than many other people do I think, but that's also idiosyncratic style.

By the way is there a reason why only `grab` has the check:
```
      if self.rc[page as usize][list as usize] == 0 {
        return None
      };
``` 
?

**Comment by ohAitch** [comment]
Nothing principled, I think `grab_mut*` are only ever called after `grab` so it would be redundant? Probably that means they would just be optimized out if you add them anyway for peace of mind.

**Comment by ronreg-ribdev** [comment]
Solid, I won't bother with it then.

**Pull request merged**
